env_id: MsPacman-v0
gamma: 0.99
buffer_capacity: 100000
batch_size: 32
lr: 2.5e-4
train_start: 5000
target_update: 5000
eps_start: 1.0
eps_end: 0.1
eps_decay_episodes: 3000
episodes: 5000
max_steps: 10000
huber: true
lr_step_size: 1000
lr_gamma: 0.95
seed: 42
gymnasium: false
device: auto
